.travis.yml
sonar-project.properties

- Correct version for SonarCloud

SDK-1472: Correct version for SonarCloud

---

README.md

- Set client API URL in README

SDK-1472: Set client API URL in README

---

README.md

NA: Correct README example

---

.gitattributes
.php_cs.dist
.phpcs.xml.dist
README.md
examples/profile/.env.example
examples/profile/.gitignore
examples/profile/README.md
examples/profile/bootstrap.php
examples/profile/composer.json
examples/profile/keys/.gitignore
examples/profile/phpunit.xml
examples/profile/tests/ProfileTest.php

SDK-1531: Profile Example

---

src/DocScan/Request/Check/SandboxCheckBuilder.php
tests/DocScan/Request/Check/SandboxDocumentAuthenticityCheckBuilderTest.php

- Rename breakdownList to breakdowns

SDK-1544: Rename breakdownList to breakdowns

---

src/Profile/Request/Attribute/SandboxDocumentDetails.php

> Flagged as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=getyoti%3Aphp-sandbox&resolved=false&types=CODE_SMELL) - the code has been simplified by replacing string concatenation with array of details parts joined together with space
- Tidied up document details value implementation

NA: Simplify construction of document details value

---

src/DocScan/Request/Check/Report/SandboxBreakdown.php
src/DocScan/Request/Check/Report/SandboxBreakdownBuilder.php
src/DocScan/Request/Check/Report/SandboxCheckReport.php
src/DocScan/Request/Check/Report/SandboxDetail.php
src/DocScan/Request/Check/Report/SandboxRecommendation.php
src/DocScan/Request/Check/Report/SandboxRecommendationBuilder.php
src/DocScan/Request/Check/SandboxCheckBuilder.php
src/DocScan/Request/Check/SandboxCheckResult.php
src/DocScan/Request/Check/SandboxDocumentTextDataCheckResult.php
tests/DocScan/Request/Check/Report/SandboxBreakdownTest.php
tests/DocScan/Request/Check/Report/SandboxDetailTest.php
tests/DocScan/Request/Check/Report/SandboxRecommendationTest.php
tests/DocScan/Request/Check/SandboxDocumentAuthenticityCheckBuilderTest.php
tests/DocScan/Request/Check/SandboxDocumentFaceMatchCheckBuilderTest.php
tests/DocScan/Request/Check/SandboxDocumentTextDataCheckBuilderTest.php
tests/DocScan/Request/Check/SandboxZoomLivenessCheckBuilderTest.php

- Renamed check report classes to be consistent with Java SDK

SDK-1544: Rename check report classes

---

.travis.yml
README.md

SDK-1395: Add SonarCloud to Travis

---

composer.json
tests/DocScan/SandboxClientTest.php
tests/TestCase.php

- Updated PHPUnit for new PHP versions

NA: Update PHPUnit for new PHP versions

---

composer.json
sonar-project.properties

Merge master 1.2.0 > development

---

examples/profile/tests/ProfileTest.php
src/Profile/Request/Attribute/SandboxDocumentImages.php
src/Profile/Request/Attribute/SandboxDocumentImagesBuilder.php
src/Profile/Request/TokenRequestBuilder.php
tests/Profile/Request/Attribute/SandboxDocumentImagesTest.php
tests/Profile/Request/TokenRequestBuilderTest.php

SDK-1499: Document Images

---

src/Profile/Request/Attribute/SandboxDocumentImagesBuilder.php

> Following #28 
- Added string type declarations to builder methods

SDK-1499: Document Images (type hints)

---

composer.json
sonar-project.properties

> Bumped minor version to `1.4.0`

Merge master 1.3.0 > development

---

.gitattributes
.github/ISSUE_TEMPLATE.md

- Issue template
We can merge back into development once this is in master

SDK-1480: GitHub config files

---

.gitattributes
.github/ISSUE_TEMPLATE.md

Merge master > development

---

tests/DocScan/Request/Check/SandboxDocumentTextDataCheckBuilderTest.php
tests/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilderTest.php

- Test coverage for nested document fields

SDK-1697: Add test coverage for nested document fields

---

composer.json

- Update PHPUnit to latest version (coverage reporting has now been fixed)

SDK-1724: Update PHPUnit

---

src/DocScan/Request/Check/SandboxDocumentTextDataCheckBuilder.php
src/DocScan/Request/Check/SandboxDocumentTextDataCheckResult.php
src/DocScan/Request/Task/SandboxDocumentIdPhoto.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilder.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskResult.php
tests/DocScan/Request/Check/SandboxDocumentTextDataCheckBuilderTest.php
tests/DocScan/Request/Task/SandboxDocumentIdPhotoTest.php
tests/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilderTest.php

SDK-1756: Document ID photo support

---

src/DocScan/Request/Task/SandboxDocumentIdPhoto.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilder.php

- Renamed data variable to reflect API

SDK-1756: Rename data variable

---

composer.json
sonar-project.properties

Merge master 1.4.0 → development

---

src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTask.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilder.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskResult.php
src/DocScan/Request/Task/SandboxTextDataExtractionReason.php
src/DocScan/Request/Task/SandboxTextDataExtractionReasonBuilder.php
src/DocScan/Request/Task/SandboxTextDataExtractionRecommendation.php
src/DocScan/Request/Task/SandboxTextDataExtractionRecommendationBuilder.php
tests/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilderTest.php
tests/DocScan/Request/Task/SandboxTextDataExtractionReasonBuilderTest.php
tests/DocScan/Request/Task/SandboxTextDataExtractionRecommendationBuilderTest.php

- Support to set in session feedback

SDK-1787: In Session Feedback

---

src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheck.php
src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckBuilder.php
src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckResult.php
src/DocScan/Request/SandboxCheckReports.php
src/DocScan/Request/SandboxCheckReportsBuilder.php
src/DocScan/Request/SandboxTaskResults.php
src/DocScan/Request/SandboxTaskResultsBuilder.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTask.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskBuilder.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskResult.php
tests/DocScan/Exception/DocScanExceptionTest.php
tests/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckBuilderTest.php
tests/DocScan/Request/SandboxCheckReportsTest.php
tests/DocScan/Request/SandboxTaskResultsTest.php
tests/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskBuilderTest.php

- Supplementary document support:
- `SandboxSupplementaryDocumentTextDataCheckBuilder`
- `SandboxSupplementaryDocumentTextDataExtractionTaskBuilder`
- `SandboxCheckReportsBuilder::withSupplementaryDocumentTextDataCheck()`
- `SandboxTaskResultsBuilder::withSupplementaryDocumentTextDataExtractionTask()`

SDK-1709: Supplementary Documents

---

.travis.yml
composer.json

- Updated `composer.json` to allow installation with PHP 8

SDK-1815: Support PHP 8

---

.travis.yml
composer.json
sonar-project.properties
src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheck.php
src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckBuilder.php
src/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckResult.php
src/DocScan/Request/SandboxCheckReports.php
src/DocScan/Request/SandboxCheckReportsBuilder.php
src/DocScan/Request/SandboxTaskResults.php
src/DocScan/Request/SandboxTaskResultsBuilder.php
src/DocScan/Request/Task/SandboxDocumentIdPhoto.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTask.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilder.php
src/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskResult.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTask.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskBuilder.php
src/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskResult.php
src/DocScan/Request/Task/SandboxTextDataExtractionReason.php
src/DocScan/Request/Task/SandboxTextDataExtractionReasonBuilder.php
src/DocScan/Request/Task/SandboxTextDataExtractionRecommendation.php
src/DocScan/Request/Task/SandboxTextDataExtractionRecommendationBuilder.php
tests/DocScan/Exception/DocScanExceptionTest.php
tests/DocScan/Request/Check/SandboxSupplementaryDocumentTextDataCheckBuilderTest.php
tests/DocScan/Request/SandboxCheckReportsTest.php
tests/DocScan/Request/SandboxTaskResultsTest.php
tests/DocScan/Request/Task/SandboxDocumentTextDataExtractionTaskBuilderTest.php
tests/DocScan/Request/Task/SandboxSupplementaryDocumentTextDataExtractionTaskBuilderTest.php
tests/DocScan/Request/Task/SandboxTextDataExtractionReasonBuilderTest.php
tests/DocScan/Request/Task/SandboxTextDataExtractionRecommendationBuilderTest.php

- Supplementary Document Support
- Support for setting in session feedback

Release 1.5.0

---

composer.json
sonar-project.properties

Bumped minor version to `1.6.0`

Merge master 1.5.0 → development

---

composer.json
sonar-project.properties
src/DocScan/Request/Check/SandboxThirdPartyIdentityCheck.php
src/DocScan/Request/Check/SandboxThirdPartyIdentityCheckBuilder.php
src/DocScan/Request/SandboxCheckReports.php
src/DocScan/Request/SandboxCheckReportsBuilder.php
tests/DocScan/Request/Check/SandboxThirdPartyIdentityCheckBuilderTest.php
tests/DocScan/Request/SandboxCheckReportsTest.php

Add third party identity check

SDK-1829-third-party-identity-check
